import { ColorCount, YearStat } from "../models";


export const canvas2024: YearStat = new YearStat(
    1912,
    305,
    642643,
    [
        new ColorCount('white', 'White', 55152),
        new ColorCount('light-grey', 'Light Grey', 20011),
        new ColorCount('medium-grey', 'Medium Grey', 13057),
        new ColorCount('deep-grey', 'Deep Grey', 12730),
        new ColorCount('dark-grey', 'Dark Grey', 12810),
        new ColorCount('black', 'Black', 119773),
        new ColorCount('dark-chocolate', 'Dark Chocolate', 5388),
        new ColorCount('chocolate', 'Chocolate', 8724),
        new ColorCount('brown', 'Brown', 6996),
        new ColorCount('peach', 'Peach', 4138),
        new ColorCount('beige', 'Beige', 8040),
        new ColorCount('pink', 'Pink', 23204),
        new ColorCount('magenta', 'Magenta', 8536),
        new ColorCount('mauve', 'Mauve', 6421),
        new ColorCount('purple', 'Purple', 12185),
        new ColorCount('dark-purple', 'Dark Purple', 10896),
        new ColorCount('navy', 'Navy', 27663),
        new ColorCount('blue', 'Blue', 34210),
        new ColorCount('azure', 'Azure', 32045),
        new ColorCount('aqua', 'Aqua', 28753),
        new ColorCount('light-teal', 'Light Teal', 5153),
        new ColorCount('dark-teal', 'Dark Teal', 5216),
        new ColorCount('forest', 'Forest', 5975),
        new ColorCount('dark-green', 'Dark Green', 12810),
        new ColorCount('green', 'Green', 15535),
        new ColorCount('lime', 'Lime', 4168),
        new ColorCount('pastel-yellow', 'Pastel Yellow', 12417),
        new ColorCount('yellow', 'Yellow', 35911),
        new ColorCount('orange', 'Orange', 12336),
        new ColorCount('rust', 'Rust', 7950),
        new ColorCount('maroon', 'Maroon', 4887),
        new ColorCount('rose', 'Rose', 8750),
        new ColorCount('red', 'Red', 54053),
        new ColorCount('watermelon', 'Watermelon', 3711)
      ],
    409046,
    81.8092,
    "https://raw.githubusercontent.com/TheRealMonte/images/main/2024/graphs/pixels-placed-per-minute.png",
    "(10,262)",
    1427,
    [
        '142446@toast.ooo: 1414 times', 
        'Kelo@lemmy.world: 7 times', 
        'hemko@lemmy.dbzer0.com: 2 times', 
        'ategon@programming.dev: 1 time', 
        'grant@grants.cafe: 1 time', 
        'EXtremeExploit@lemmy.world: 1 time', 
        'hdggDalton@toast.ooo: 1 time'
    ],
    "https://raw.githubusercontent.com/TheRealMonte/images/main/2024/graphs/heatmap-with-legend.png",
    15724,
    1101,
    13,
    'https://raw.githubusercontent.com/TheRealMonte/images/main/2024/final2024.png',
    "https://atlas.mariusdavid.fr/"
);

export const canvas2023: YearStat = new YearStat(
    2204,
    132,
    628416,
    [
        new ColorCount('white', 'White', 22488),
        new ColorCount('light-grey', 'Light Grey', 20308), 
        new ColorCount('medium-grey', 'Medium Grey', 15799), 
        new ColorCount('medium-grey', 'Deep Grey', 13864), 
        new ColorCount('dark-grey', 'Dark Grey', 19708), 
        new ColorCount('black', 'Black', 123666), 
        new ColorCount('chocolate', 'Chocolate', 9669), 
        new ColorCount('brown', 'Brown', 8535), 
        new ColorCount('peach', 'Peach', 5790), 
        new ColorCount('beige', 'Beige', 4821), 
        new ColorCount('pink', 'Pink', 18566), 
        new ColorCount('magenta', 'Magenta', 4554), 
        new ColorCount('mauve', 'Mauve', 10180), 
        new ColorCount('purple', 'Purple', 17346), 
        new ColorCount('navy', 'Navy', 17594), 
        new ColorCount('blue', 'Blue', 58856), 
        new ColorCount('azure', 'Azure', 33653), 
        new ColorCount('aqua', 'Aqua', 12588), 
        new ColorCount('light-teal', 'Light Teal', 5695), 
        new ColorCount('dark-teal', 'Dark Teal', 4701), 
        new ColorCount('forest', 'Forest', 9478), 
        new ColorCount('dark-green', 'Dark Green', 19377), 
        new ColorCount('green', 'Green', 12612), 
        new ColorCount('lime', 'Lime', 5585), 
        new ColorCount('pastel-yellow', 'Pastel Yellow', 8543), 
        new ColorCount('yellow', 'Yellow', 32473), 
        new ColorCount('orange', 'Orange', 14841), 
        new ColorCount('rust', 'Rust', 19064), 
        new ColorCount('maroon', 'Maroon', 4218), 
        new ColorCount('rose', 'Rose', 10948), 
        new ColorCount('red', 'Red', 55683), 
        new ColorCount('watermelon', 'Watermelon', 7213)
    ],
    541666,
    54.1666,
    "https://raw.githubusercontent.com/TheRealMonte/images/main/2023/graphs/pixels-placed-per-minute.png",
    "(175, 171)",
    170,
    [
        'Depress_mode@lemmy.world: 83 times', 
        'Kalcifer@lemmy.world: 77 times', 
        'anonymous1691293996@lemmy.world: 4 times', 
        'anonymous1691294527@lemmy.world: 3 times', 
        'anonymous1691296202@lemmy.world: 1 time', 
        'bstix@feddit.dk: 1 time', 
        'Wilker@lemmy.blahaj.zone: 1 time'
    ],
    "https://raw.githubusercontent.com/TheRealMonte/images/main/2023/graphs/heatmap-with-legend.png",
    10715,
    1000,
    4,
    "https://raw.githubusercontent.com/TheRealMonte/images/main/2023/final2023.png",
    undefined
)